services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    
  # llama-server:
  #   image: ghcr.io/ggml-org/llama.cpp:server
  #   container_name: llama-gemma   
  #   ports:  
  #     - "50000:50000"
  #   volumes:
  #     - /mnt/c/Users/ASUS/.cache/huggingface:/root/.cache/huggingface
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   command: >
  #     -hf unsloth/gemma-4-E2B-it-GGUF 
  #     --port 50000 
  #     --host 0.0.0.0
  #     --metrics
  #     -c 4096 
  #     -np 5
  #   restart: unless-stopped

  vllm-server:
    image: vllm/vllm-openai:gemma4
    container_name: vllm-gemma4
    ipc: host
    network_mode: host
    shm_size: '16gb'
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      --model gemma-4-E2B-it
      --tensor-parallel-size 1
      --max-model-len 4096
      --gpu-memory-utilization 0.90
      --host 0.0.0.0
      --port 50001

volumes:
  grafana-storage:
  prometheus-data: